### PR TITLE
easier to read + disable edit

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
@barrykooij Are you maintaining this repo?

**Comment by barrykooij** [comment]
Thanks for the mention, I don't get emails for PR's :/

**Comment by barrykooij** [comment]
Implemented this in a slightly different way, thanks for this.
69375d78b2c8e3cda6e29b4fb5238c75dfef968f

**Comment by szepeviktor** [comment]
Yours is more abstract.

**Pull request closed without merging**
